---
title: "test"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
math_final_grade <- read_csv2("student/student-mat.csv")
glimpse(math_final_grade)
```


```{r}
#This function is used to check the correlation between G3 and other categorical variables
# 定义一个函数，用于检验 G3 与每个分类变量的 ANOVA 结果
anova_test <- function(math_final_grade, target = "G3") {
  results <- data.frame(
    variable = character(),
    p_value = numeric(),
    stringsAsFactors = FALSE
  )
  
  for (var in names(math_final_grade)) {
    if (is.factor(math_final_grade[[var]]) || is.character(math_final_grade[[var]])) {
      formula <- as.formula(paste(target, "~", var))
      fit <- aov(formula, data = math_final_grade)
      p_val <- summary(fit)[[1]][["Pr(>F)"]][1]
      results <- rbind(results, data.frame(variable = var, p_value = p_val))
    }
  }
  
  # 按显著性排序
  results <- results[order(results$p_value), ]
  return(results)
}

# 调用函数
anova_results <- anova_test(math_final_grade, "G3")

# 查看所有显著结果（p < 0.05）
anova_results[anova_results$p_value < 0.05, ]
```

```{r}
library(dplyr)

num_df <- math_final_grade |> select(where(is.numeric))
r_with_G3 <- cor(num_df, use = "pairwise.complete.obs", method = "pearson")["G3", ]
sort(r_with_G3[ names(r_with_G3) != "G3" ], decreasing = TRUE)  # 排序查看强到弱

```


```{r}
library(ggplot2)
library(ggfortify)

model1 <- lm(G3 ~ G1 + age + Medu + Fedu + G2, data=math_final_grade) #cor>0.15


autoplot(model1, which = 1:2, ncol = 2)
```


```{r}
math_final_grade <- math_final_grade %>% filter(G3 != 0 )
```

```{r}
model2 <- lm(G3 ~ G1 + age + Medu + Fedu + G2 + failures, data=math_final_grade) #cor>0.15
autoplot(model2, which = 1:2, ncol = 2)
```


```{r}
math_final_grade <- math_final_grade %>%
  mutate(failures_log = log(failures + 1))
```

```{r}
math_final_grade <- math_final_grade %>%
  mutate(absences_log = log(absences + 1))
```


```{r}

math_final_grade <- math_final_grade %>%
  mutate(G1_log = log(G1+1))
```


```{r}
math_final_grade <- math_final_grade %>%
  mutate(famrel_log = log(famrel+1))
```

```{r}
math_final_grade <- math_final_grade %>%
  mutate(G2_log = log(G2+1))
```

```{r}
math_final_grade <- math_final_grade %>%
  mutate(G3_log = log(G3+1))
```


```{r}
model3 <- lm(sqrt(G3) ~ failures + G1 + G2 + Fedu + Medu + log(age+1), data=math_final_grade)
autoplot(model3, which = 1:2, ncol = 2)
```
```{r}
library(car)

vif_values <- vif(model3)
vif_df <- data.frame(
  Variable = names(vif_values),
  GVIF = vif_values,
  Df = 1,
  `GVIF^(1/(2*Df))` = vif_values^(1/(2*1))
)

print(vif_df)

```



```{r}
model4 <- lm(sqrt(G3) ~ failures + G1 + Fedu + Medu + log(age+1) + absences ,  data=math_final_grade)
autoplot(model3, which = 1:2, ncol = 2)
```
```{r}
summary(model4)
```



```{r}
step.back.aic = step(model4, 
                     direction = "backward", 
                     trace = FALSE)
round(summary(step.back.aic)$coef,3)
```

```{r}
autoplot(step.back.aic, which = 1:2, ncol = 2)
```



